name: Build and Push All MLOps Images

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - service_name: backend
            context: ./api
            dockerfile: ./api/Dockerfile.backend
            image_suffix: backend
          - service_name: ui
            context: ./ui
            dockerfile: ./ui/Dockerfile
            image_suffix: ui
          - service_name: training
            context: ./training
            dockerfile: ./training/Dockerfile
            image_suffix: training
          - service_name: mlflow
            context: ./mlflow
            dockerfile: ./mlflow/Dockerfile
            image_suffix: mlflow
          - service_name: builder
            context: ./api
            dockerfile: ./api/Dockerfile.builder
            image_suffix: builder
          - service_name: base
            context: ./api
            dockerfile: ./api/Dockerfile.base
            image_suffix: base

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 1. QEMU 설정
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.image_suffix }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max